docs/tsconfig/it/options/allowSyntheticDefaultImports.md
docs/tsconfig/it/options/allowUmdGlobalAccess.md
docs/tsconfig/it/options/allowUnreachableCode.md

Files: 
- allowUnreachableCode.md
- allowUmdGlobalAccess.md
- SyntheticDefaultImports.md

TSConfig Italian translation: added files

---

docs/tsconfig/ko/options/composite.md
docs/tsconfig/ko/options/listFiles.md

en :
[checkJs.md](https://github.com/microsoft/TypeScript-Website/blob/v2/packages/tsconfig-reference/copy/en/options/checkJs.md)  해당파일은 이미 다른분이 PR 하신거 같아 번역을 진행하지 않았습니다.
[composite.md](https://github.com/microsoft/TypeScript-Website/blob/v2/packages/tsconfig-reference/copy/en/options/composite.md)
[listFiles.md](https://github.com/microsoft/TypeScript-Website/blob/v2/packages/tsconfig-reference/copy/en/options/listFiles.md)
번역 리뷰 요청합니다 : @yeonjuan @guyeol @dvlprsh
감사합니다!
ref #6

translation 2 files to Ko

---

docs/playground/ko/JavaScript/JavaScript Essentials/Code Flow.ts

en
* [Code Flow.ts](https://github.com/microsoft/TypeScript-Website/blob/v2/packages//playground-examples/copy/en/JavaScript/JavaScript%20Essentials/Code%20Flow.ts)
번역 리뷰 요청합니다: @yeonjuan @guyeol @dvlprsh
ref #6
감사합니다 😃

Translate 1 file to ko - Code Flow

---

docs/tsconfig/pt/options/explainFiles.md

[PT-BR] explainFiles.md

---

docs/tsconfig/ko/options/out.md
docs/tsconfig/ko/options/outDir.md
docs/tsconfig/ko/options/outFile.md

en
- [out.md](https://github.com/microsoft/TypeScript-Website/blob/v2/packages//tsconfig-reference/copy/en/options/out.md)
- [outDir.md](https://github.com/microsoft/TypeScript-Website/blob/v2/packages/tsconfig-reference/copy/en/options/outDir.md)
- [outFile.md](https://github.com/microsoft/TypeScript-Website/blob/v2/packages/tsconfig-reference/copy/en/options/outFile.md)
번역 리뷰 요청합니다: @yeonjuan @guyeol @dvlprsh
ref #6
감사합니다! 😎

Translate 3 files to ko - out, outDir, outFile

---

docs/documentation/pl/Nightly Builds.md

[PL] nightly builds translation

---

docs/tsconfig/ja/options/disableReferencedProjectLoad.md
docs/tsconfig/ja/options/jsxFragmentFactory.md
docs/tsconfig/ja/options/jsxImportSource.md
docs/tsconfig/ja/options/noUncheckedIndexedAccess.md
docs/tsconfig/ja/options/watchDirectory.md
docs/tsconfig/ja/options/watchFile.md
docs/tsconfig/ja/sections/compilerOptions.md
docs/tsconfig/ja/sections/top_level.md

ref: #3 
以前、https://github.com/microsoft/TypeScript-Website/pull/1432 でレビューをいただいてマージしてもらったのですが、こちらのリポジトリに反映されていなかったので再掲です
diff: 23d4826

[ja] tsconfig/options, tsconfig/sections

---

docs/playground/ko/JavaScript/Working With Classes/Mixins.ts

en
* [Mixins.ts](https://github.com/microsoft/TypeScript-Website/blob/v2/packages//playground-examples/copy/en/JavaScript/Working%20With%20Classes/Mixins.ts)
ref #6
감사합니다 😃

Translate 1 file to ko - Mixins

---

docs/documentation/ko/reference/Module Resolution.md

- Removed unnecessary html tags.

[ko] Fix typo - Module Resolution

---

.github/CODEOWNERS
README.md
localize.json
starting_new_language.md
welcome.md

This adds the necessary bits for French language support in the repo (and the TS site)

Adds French language support

---

docs/typescriptlang/fr/dt.ts
docs/typescriptlang/fr/fr.ts
docs/typescriptlang/fr/handbook.ts
docs/typescriptlang/fr/head-seo.ts
docs/typescriptlang/fr/nav.ts

Le lien vers les fichiers en Anglais -> [microsoft/TypeScript-Website](https://github.com/microsoft/TypeScript-Website/tree/v2/packages/typescriptlang-org/src/copy/en)
J'ai traduit `handbook` par `Guide`, je ne me voyais pas mettre documentation/doc. J'ai laissé playground en anglais... Je ne sais pas quoi mettre (`éditeur en ligne` ou `éditeur` tout simplement peut etre)

Translate to FR: typescriptlang directory

---

docs/tsconfig/ko/options/noResolve.md

issue : #6 
en : [noResolve.md](https://github.com/microsoft/TypeScript-Website/blob/v2/packages/tsconfig-reference/copy/en/options/noResolve.md)
TSConfig noResolve 번역 완료하였습니다.
리뷰나 수정사항있다면 코멘트 부탁드립니다!

Translate 1 file to ko, TSConfig - noResolve

---

docs/tsconfig/ko/options/moduleResolution.md

issue : #6 
en : [moduleResolution.md](https://github.com/microsoft/TypeScript-Website/blob/v2/packages/tsconfig-reference/copy/en/options/moduleResolution.md)
TSConfig moduleResolution.md 번역 완료하였습니다.
리뷰나 수정사항있다면 코멘트 부탁드립니다!

Translate 1 file to ko, TSConfig - moduleResolution

---

docs/documentation/pt/declaration-files/By Example.md
docs/documentation/pt/declaration-files/Do's and Don'ts.md

This PR translates the following documentation to Brazilian Portuguese.
- Example.md
- Do's and Dont's.md
I have translated Do's and Dont's to `Sempre` e `Nunca`. I know that it may look weird, but reads more natural in Portuguese.
Some exemples: 
> _Don't_ ever use the types `Number`, `String`, `Boolean`, `Symbol`, or `Object`
to
> _Nunca_ use os tipos `Number`, `String`, `Boolean`, `Symbol`, ou `Object`
Ref: #1

[PT-BR] By Example.md and Do's and Dont's.md

---

docs/playground/ko/TypeScript/Meta-Types/Discriminate Types.ts

en
* [Discriminate Types.ts](https://github.com/microsoft/TypeScript-Website/blob/v2/packages//playground-examples/copy/en/TypeScript/Meta-Types/Discriminate%20Types.ts)
ref #6
감사합니다 😃

Translate 1 file to ko. playground-Discriminate Types

---

docs/documentation/id/reference/JSX.md

Fix typo in 'opeartor' to 'operator'

Fix typo in JSX.md

---

docs/playground/fr/3-7/Syntax and Messaging/Optional Chaining.ts

Fix some missing words. See [comment](https://github.com/microsoft/TypeScript-Website-Localizations/pull/114#discussion_r684650542)

FR translation: fix typo

---

docs/playground/ko/TypeScript/Language Extensions/Nominal Typing.ts

en
* [Nominal Typing.ts](https://github.com/microsoft/TypeScript-Website/blob/v2/packages//playground-examples/copy/en/TypeScript/Language%20Extensions/Nominal%20Typing.ts)
ref #6
감사합니다 😄

Translate 1 file to ko, playground - Nominal Typing

---

docs/playground/ko/3-7/Types and Code Flow/Uncalled Function Checks.ts

#6 
Uncalled Function Checks를 번역하였습니다. 검수 부탁드립니다.
@yeonjuan
추가적으로, 용어집에 '블록'이 추가되면 좋을 것 같습니다. 자주 등장할 것 같은 단어인 것 같습니다.
국립국어원 발음표기에 따라 '블락', '블럭'이 아닌 '블록'으로 표현하는 것이 옳다고 합니다.

Translate 1 file to ko - Uncalled Function Checks

---

docs/documentation/ko/get-started/TS for Functional Programmers.md

안녕하세요! 리뷰 부탁드립니다!
- 수정 파일 : [docs/documentation/ko/get-started/TS for Functional Programmers.md](https://github.com/microsoft/TypeScript-Website-Localizations/blob/main/docs/documentation/ko/get-started/TS%20for%20Functional%20Programmers.md)
- _내용 1: 유니언 타입 (Unit types) 부분에서 유닛 타입이 적절해보입니다._
- **AS-IS** : `유니언` 타입 (Unit types)
**TO-BE**: `유닛` 타입 (Unit types)
- **AS-IS**: `유니언` 타입은 정확히 하나의 원시 값을 포함하고 있는 원시 타입의 서브타입입니다.
**TO-BE**: `유닛` 타입은 정확히 하나의 원시 값을 포함하고 있는 원시 타입의 서브타입입니다.
- _내용 2: 내장 타입 (Built-in types)에서 `BigInt` 가 누락되었습니다._
- **AS-IS**: 
JavaScript에서는 `7`개의 내장 타입을 정의합니다:
**TO-BE**: (Change)
JavaScript에서는 `8`개의 내장 타입을 정의합니다:
**EN**: 
JavaScript defines 8 built-in types:
- **AS-IS**:
| 타입 | 설명 |
|-|-|
|...|...|
**TO-BE**: (Add)
| 타입 | 설명 |
|-|-|
| `BigInt` | 임의 정밀도 형식의 정수. |
**EN**:
| …

Update Ts for Functional Programmers.md

---

docs/documentation/ko/get-started/TS for JS Programmers.md

Fix some missing words.
오타가 있어 수정합니다.
`추기해` -> `추가해`

[ko] Fix typo in 'TypeScript for JavaScript Programmers'

---

docs/documentation/ko/javascript/Creating DTS files From JS.md

I found a typo in [document](https://www.typescriptlang.org/ko/docs/handbook/declaration-files/dts-from-js.html#packagejson-수정-editing-the-packagejson).
As I compare with English document, `./main/main.d.ts` should be `./dist/main.d.ts`.
As-is: 
| Package.json              | 기본 .d.ts의 위치                 |
| :------------------------ | :----------------------------- |
| "types" 필드 없음           | "main" 확인 후, index.d.ts 확인   |
| "types": "main.d.ts"      | main.d.ts                      |
| "types": "./dist/main.js" | **_./main/main.d.ts_**               |
To-be:
| Package.json              | 기본 .d.ts의 위치                 |
| :------------------------ | :----------------------------- |
| "types" 필드 없음           | "main" 확인 후, index.d.ts 확인   |
| "types": "main.d.ts"      | main.d.ts …

Fix typo in korean documentation

---

docs/playground/ko/4-0/New TS Features/Unknown in Catch.ts

Unknown in Catch를 한국어로 번역했습니다.

Translate Unknown in Catch

---

docs/typescriptlang/fr/cheatsheets.ts
docs/typescriptlang/fr/community.ts
docs/typescriptlang/fr/documentation.ts
docs/typescriptlang/fr/dt.ts
docs/typescriptlang/fr/footer.ts
docs/typescriptlang/fr/fr.ts
docs/typescriptlang/fr/handbook.ts
docs/typescriptlang/fr/head-seo.ts
docs/typescriptlang/fr/index.ts
docs/typescriptlang/fr/index2.ts
docs/typescriptlang/fr/nav.ts
docs/typescriptlang/fr/playground.ts

Added translations for the typescriptlang directory.

Added French typescriptlang translations

---

docs/documentation/ko/handbook-v2/Type Manipulation/Keyof Type Operator.md

https://github.com/microsoft/TypeScript-Website-Localizations/commit/090674716fecd8e5af4f286a9ebe89b84bda50e3
리뷰 부탁드려요~

Translate 1 file to ko - Keyof Type Operator.md

---

docs/documentation/ko/release-notes/TypeScript 3.8.md
docs/documentation/ko/release-notes/TypeScript 3.9.md

In the Korean release notes document, toc malfunctions due to unnecessary span tags.
- https://www.typescriptlang.org/ko/docs/handbook/release-notes/typescript-3-8.html
- https://www.typescriptlang.org/ko/docs/handbook/release-notes/typescript-3-9.html

Remove span tag in title and unnecessary TOC in Ko

---

docs/documentation/ko/handbook-v2/Everyday Types.md

예제 코드들 중에 `---cut---`이라는 특수 문구까지 `---중간 생략---`으로 번역해서 의도치 않은 타입 선언문들이 보여서 읽을 때 혼란을 주어서 원복합니다. 🙏 
그리고 일부 헤딩 크기가 영어 원본과 다르게 한단계씩 작게 표시하고 있어서, 이 부분들도 같이 복구합니다.

Fix typo in Everyday Types in Korean

---

docs/documentation/ko/tutorials/Babel with TypeScript.md

안녕하세요, 잘못 번역된 부분이 있는 것 같아 수정했습니다. 리뷰 부탁드립니다.
[docs/documentation/ko/tutorials/Babel with TypeScript.md](https://github.com/microsoft/TypeScript-Website-Localizations/blob/main/docs/documentation/ko/tutorials/Babel%20with%20TypeScript.md)
AS-IS : 프레임워크를 사용하여 프로젝트를 만들고 있다면 **결정은 여러분 손에 달려있습니다.**
TO-BE: 프레임워크를 사용하여 프로젝트를 만들고 있다면 **이 결정은 여러분을 위해 자동으로 처리됩니다.**

Fix mistranslated sentence

---

docs/documentation/ko/handbook-v2/Type Manipulation/Indexed Access Types.md

https://github.com/microsoft/TypeScript-Website-Localizations/commit/45a33fe429604220c6be9ff68e01ab7798e658cb
리뷰 부탁드려요~
추가로 `index`를 "색인화" 말고 그냥 인덱스라고 번역했는데 어떤가요??
의견 부탁드립니다.

Translate 1 file to ko - Indexed Access Types.md

---

docs/documentation/ko/release-notes/TypeScript 4.9.md

https://github.com/microsoft/TypeScript-Website-Localizations/pull/192#issuecomment-1356036278

Rename property  in ts 4.9 satisfies section
