microsoft/TypeScript-Website-Localizations

docs/tsconfig/it/options/importHelpers.md
docs/tsconfig/it/options/incremental.md
docs/tsconfig/it/options/isolatedModules.md

Files:
- importHelpers.md
- incremental.md
- isolatedModules.md

TSConfig Italian Translation: some files

---

docs/tsconfig/it/options/downlevelIteration.md
docs/tsconfig/it/options/jsx.md
docs/tsconfig/it/options/module.md

Files added:
- dowmlevelIteration.md
- jsx.md
- module.md

TSConfig Italian translation: added various files

---

docs/tsconfig/it/options/target.md
docs/tsconfig/it/options/tsBuildInfoFile.md

Added:
- target.md
- tsBuildInfoFile.md

TS Congfig Options Italian translation: Added some files.

---

docs/tsconfig/it/options/rootDir.md
docs/tsconfig/it/options/sourceMap.md

Files: 
- rootDir.md
- sourceMap.md

TSConfig Italian Translation: added some files

---

docs/tsconfig/it/options/sourceMap.md

Fixed oneline error on file `sourceMap.md`

TSConfig Italian Translation: Fixed oneline error

---

docs/tsconfig/it/options/target.md

TSConfig Italian Transaltion: Few fixes

---

docs/playground/ko/JavaScript/Helping with JavaScript/Quick Fixes.ts

en
* [Quick Fixes 101.ts](https://github.com/microsoft/TypeScript-Website/blob/v2/packages//playground-examples/copy/en/JavaScript/Helping%20with%20JavaScript/Quick%20Fixes.ts)
번역 리뷰 요청합니다: @yeonjuan @guyeol @dvlprsh
ref #6
감사합니다 😃

Translate 1 file to ko - Quick Fixes

---

docs/tsconfig/pt/options/noPropertyAccessFromIndexSignature.md

Translation from en to pt
@khaosdoctor e @danilofuchs

[PT-BR] noPropertyAccessFromIndexSignature.md

---

docs/typescriptlang/ja/community.ts
docs/typescriptlang/ja/handbook.ts
docs/typescriptlang/ja/ja.ts

Add
- handbook.ts
- tsconfig.ts
Update
- community.ts
- ja.ts

Update Japanese translation files

---

docs/documentation/ko/declaration-files/templates/module-class.d.ts.md
docs/documentation/ko/declaration-files/templates/module-function.d.ts.md
docs/documentation/ko/reference/Decorators.md
docs/documentation/ko/reference/Enums.md
docs/documentation/ko/reference/Module Resolution.md
docs/documentation/ko/reference/Modules.md
docs/documentation/ko/reference/Namespaces and Modules.md
docs/documentation/ko/reference/Namespaces.md
docs/documentation/ko/reference/Type Compatibility.md
docs/documentation/ko/reference/Variable Declarations.md
docs/documentation/ko/tutorials/ASP.NET Core.md
docs/documentation/ko/tutorials/DOM Manipulation.md
docs/documentation/ko/tutorials/Gulp.md
docs/documentation/ko/tutorials/Migrating from JavaScript.md

- This PR adds files from [old Korean repo](https://github.com/typescript-kr/typescript-kr.github.io).
- Related PR: #53

Add files from old Korean repo to ko

---

docs/documentation/pt/declaration-files/Consumption.md

[PT-BR] Consumption.md

---

docs/documentation/ko/reference/Utility Types.md

[ko] Update ko/docs/handbook/utility-types.html

---

docs/playground/ko/JavaScript/Working With Classes/Generic Classes.ts

en
* [Generic Classes.ts](https://github.com/microsoft/TypeScript-Website/blob/v2/packages//playground-examples/copy/en/JavaScript/Working%20With%20Classes/Generic%20Classes.ts)
ref #6
감사합니다 😃

Translate 1 file to ko - Generic Classes

---

docs/documentation/zh/project-config/tsconfig.json.md

Translate 1 file to zh - tsconfig.json

---

docs/playground/ko/TypeScript/Type Primitives/Built-in Utility Types.ts

en
* [Built in Utility Types.ts](https://github.com/microsoft/TypeScript-Website/blob/v2/packages//playground-examples/copy/en/TypeScript/Type%20Primitives/Built-in%20Utility%20Types.ts)
ref #6
감사합니다 😃

Translate 1 file to ko - Built in Utility Types

---

docs/typescriptlang/fr/community.ts

First FR entry in `typescriptlang` (`community.ts`)

Translate 1 file to FR, typescriptlang - community

---

docs/playground/fr/3-7/Fixits/Big number literals.ts
docs/playground/fr/3-7/Fixits/Const to let.ts
docs/playground/fr/3-7/Fixits/Infer From Usage Changes.ts

Translate remaining files from the playground/en/3-7/Fixits folder to french

Translate to FR: playground/3-7/fixits

---

docs/documentation/fr/tutorials/Angular.md
docs/documentation/fr/tutorials/React.md

- J'ai traduit "seamless experience" en "expérience fluide" merci de proposer d'autre traduction plus adapté si possible
- J'ai traduit "TypeScript as a first-class citizen" en "objet de première classe" en partant du wiki: https://fr.wikipedia.org/wiki/Objet_de_premi%C3%A8re_classe, même si d'autre références remplace "objet" par "citoyen"(https://www.microsoft.com/en-us/research/publication/unboxed-values-as-first-class-citizens/). "Objet" me semble plus parlant.

translate Angular.md file

---

docs/playground/ko/Playground/Tooling/TypeScript Versions.ts

issue: #6 
- [TypeScript Versions](https://github.com/microsoft/TypeScript-Website/blob/v2/packages/playground-examples/copy/en/Playground/Tooling/TypeScript%20Versions.ts)
맞춤법 검사기로 한번 체크하였습니다~ 혹시 확인하시다가 수정해야할 사항 있다면 코멘트 부탁드립니다!

Translate 1 file to ko - Typescript Version

---

docs/documentation/pt/declaration-files/Deep Dive.md

[PT-BR] Deep Dive

---

docs/playground/ko/TypeScript/Meta-Types/Indexed Types.ts

en
* [Indexed Types.ts](https://github.com/microsoft/TypeScript-Website/blob/v2/packages//playground-examples/copy/en/TypeScript/Meta-Types/Indexed%20Types.ts)
ref #6
감사합니다 😃

Translate 1 file to ko. playground Indexed Types

---

docs/documentation/pt/declaration-files/Introduction.md

[PT-BR] Translate file Introduction

---

docs/playground/fr/3-7/Syntax and Messaging/Flattened Error Reporting.ts
docs/playground/fr/3-7/Syntax and Messaging/Nullish Coalescing.ts
docs/playground/fr/3-7/Syntax and Messaging/Optional Chaining.ts

Translates to french the files from playground/en/3-7/Syntax and messaging.

Translate FR: playground/fr/3-7/Syntax and messaging

---

docs/playground/pt/TypeScript/Language Extensions/Types vs Interfaces.ts

Fixing error in the translation of the word "própria".

fix: correcting text in PT-br

---

docs/typescriptlang/ko/community.ts
docs/typescriptlang/ko/ko.ts
docs/typescriptlang/ko/nav.ts
localize.json

[ko] Add some Korean translations

---

docs/documentation/ko/handbook-v2/Type Manipulation/Mapped Types.md

https://github.com/microsoft/TypeScript-Website-Localizations/pull/132/commits/93cf0c9ec55210ae34d593b21804bd5150fe2faa
번역 확인 부탁드려요~

Translate 1 file to ko - Mapped Types.md

---

docs/documentation/pt/declaration-files/templates/global-modifying-module.d.ts.md

 [PT-BR] global-modifying-modules.d.ts

---

docs/documentation/ko/handbook-v2/Basics.md

Fix typo in `Basics`

---

docs/documentation/pt/get-started/TS for the New Programmer.md

Fixes the word "Programados" to "Programador" on title

fix: fixes the word 'Programados' to 'Programador'
